import { request } from '@/utils'

export default {
  getList: (params = {}) => request.get('/gmail/list', { params }),
  create: (data = {}) => request.post('/gmail/create', data),
  update: (data = {}) => request.post('/gmail/update', data),
  assign: (data = {}) => request.post('/gmail/assign', data),
  autoAssign: (siteId) => request.post('/gmail/auto-assign', { site_id: siteId }),
  batchAutoAssign: (siteIds) => request.post('/gmail/batch-auto-assign', { site_ids: siteIds }),
  unassign: (siteId) => request.post('/gmail/unassign', { site_id: siteId }),
  batchCreate: (items = []) => request.post('/gmail/batch-create', items),
  batchAssign: (data = {}) => request.post('/gmail/batch-assign', data),
  batchDelete: (ids = []) => request.post('/gmail/batch-delete', ids),
  setHealthStatus: (data = {}) => request.post('/gmail/set-health', data),

  // ── Gmail 注册 ──
  regGetList: (params = {}) => request.get('/gmail/registration/list', { params }),
  regCreate: (data = {}) => request.post('/gmail/registration/create', data),
  regAvailableOutlook: (params = {}) => request.get('/gmail/registration/available-outlook', { params }),
  regUpdateTwoFaKey: (data = {}) => request.post('/gmail/registration/update-two-fa-key', data),
  regAssignOutlook: (data = {}) => request.post('/gmail/registration/assign-outlook', data),
  regBatchAssignOutlook: (data = {}) => request.post('/gmail/registration/batch-assign-outlook', data),
  regBatchUpdateStatus: (data = {}) => request.post('/gmail/registration/batch-update-status', data),
  regCreateForwarding: (data = {}) => request.post('/gmail/registration/create-forwarding', data),
  regCreateEnv: (data = {}) => request.post('/gmail/registration/create-env', data),
  regGetPhone: (data = {}) => request.post('/gmail/registration/get-phone', data),
  regWaitSms: (data = {}) => request.post('/gmail/registration/wait-sms', data),
  regConfirmSms: (data = {}) => request.post('/gmail/registration/confirm-sms', data),
  regBatchDelete: (ids = []) => request.post('/gmail/registration/batch-delete', ids),
  regBatchFetch: (data = {}) => request.post('/gmail/registration/batch-fetch', data),
  regBatchAssignEnv: (data = {}) => request.post('/gmail/registration/batch-assign-env', data),
  regBatchCreateForwarding: (ids = []) => request.post('/gmail/registration/batch-create-forwarding', ids),
  regBatchCreateEnv: (ids = []) => request.post('/gmail/registration/batch-create-env', ids),
  regBatchGetPhone: (ids = []) => request.post('/gmail/registration/batch-get-phone', ids),
  regBatchWaitSms: (ids = [], timeout = 60) => request.post('/gmail/registration/batch-wait-sms', ids, { params: { timeout } }),
  regBatchConfirmSms: (ids = []) => request.post('/gmail/registration/batch-confirm-sms', ids),
}
